// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwrXfbb3u-geQPsdyJsMCuzVKNGSAdDY',
    appId: '1:397252163249:web:f17c7a39707ff61f2cd490',
    messagingSenderId: '397252163249',
    projectId: 'education-flutter-app-acd97',
    authDomain: 'education-flutter-app-acd97.firebaseapp.com',
    storageBucket: 'education-flutter-app-acd97.appspot.com',
    measurementId: 'G-VVNNXS61EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ0klxIzhM-Ww09M9HUm-WZ_hT_isXRiM',
    appId: '1:397252163249:android:96f658e3d26796242cd490',
    messagingSenderId: '397252163249',
    projectId: 'education-flutter-app-acd97',
    storageBucket: 'education-flutter-app-acd97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVzsG5LdgQYhuAuH4fdzX4H_PQALqBaiY',
    appId: '1:397252163249:ios:76258e7c15d619532cd490',
    messagingSenderId: '397252163249',
    projectId: 'education-flutter-app-acd97',
    storageBucket: 'education-flutter-app-acd97.appspot.com',
    iosBundleId: 'com.example.flutterJobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVzsG5LdgQYhuAuH4fdzX4H_PQALqBaiY',
    appId: '1:397252163249:ios:76258e7c15d619532cd490',
    messagingSenderId: '397252163249',
    projectId: 'education-flutter-app-acd97',
    storageBucket: 'education-flutter-app-acd97.appspot.com',
    iosClientId: '397252163249-gtu1n3253qh88i63r5fc7tutnmbe851d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJobApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFwrXfbb3u-geQPsdyJsMCuzVKNGSAdDY',
    appId: '1:397252163249:web:682f1184e558c1742cd490',
    messagingSenderId: '397252163249',
    projectId: 'education-flutter-app-acd97',
    authDomain: 'education-flutter-app-acd97.firebaseapp.com',
    storageBucket: 'education-flutter-app-acd97.appspot.com',
    measurementId: 'G-C13W7QGYYR',
  );
}
